### ISSUE TITLE
Account password reset on Windows Edge

### ISSUE THREAD

**Issue by HYDETS38** [yalla-coop/cost-of-living-support#250] opened 2023-01-24 09:09 UTC
Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)

When requesting a password reset, there is no email being sent. At this time there have been 10+ requests sent. 
relevant link https://col-helper.co.uk/forget-password 

Unfortunately as the accounts have been changed during transfer from Maggie, it is necessary to change logins. Unfortunately this is not possible without the links.

**Team - do not edit**
@thejoefriel

**Comment by cyberteenie** [comment] 2023-02-02 17:10
Hi @HYDETS38 - we will look into this ASAP! We will keep you updated!

**Comment by HYDETS38** [comment] 2023-02-09 07:45
Update.
Emails received at the moment with the intended link to reset the password, contain a text string in blue font, which is supposed to be a link, but it's just text. Manually copy-paste sends me to the main CoL landing page, not to the login one.
So at the moment I can't access our account.

**Comment by cyberteenie** [comment] 2023-02-09 14:54
@HYDETS38 Thanks for the update, we will look into this asap.

**Comment by thejoefriel** [comment] 2023-02-09 14:59
UPDATE
The issue is only on Windows Edge. What happens is when you click the link it seems to redirect you to the home page. Tomi agrees this is lower priority right now, so something to look at later

**Comment by Katie-Hyde** [comment] 2023-07-26 13:30
**still an issue please  escalate** 
I’m using Google Chrome- and yes, its just that when I click ‘forgot password’ and enter either of my email addresses, it doesn’t send an email. Have checked both my inboxes and junk folders just now, and still no password reset.

**Comment by Katie-Hyde** [comment] 2023-08-03 07:33
Can i have an update on this bug please as i have new organisations signing up that can't access. We are also launching a big marketing push in October so needs to be fixed and tested prior

**Comment by RamyAlshurafa** [comment] 2023-08-03 09:09
Hi @Katie-Hyde 
The issue with email being not clicked should be fixed now, 
and also tested the reset password functionality and it works, 

for this organisation having troubles:
- whats the email address they use?
- are they not getting a reset password or its another issue?

**Comment by cyberteenie** [comment] 2023-08-25 09:35
Hi @Katie-Hyde - just wanted to double check as it seemed from our call that this issue is now solved for you. Have I understood that correct?

@RamyAlshurafa did the fix you do also work for Windows Edge?

**Comment by Katie-Hyde** [comment] 2023-08-29 10:41
Hi Kristina

Had another password issue over the weekend with comments though HotJar, added new issue to git hub

Katie

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by RamyAlshurafa** [comment] 2023-08-30 12:03
Hey @Katie-Hyde and thanks for reporting,
what is the email address they are trying to reset the password for?

**Comment by cyberteenie** [comment] 2023-10-23 05:56
@Katie-Hyde - closing this issue for now, but please feel free to reopen if there are any other issues. Thanks!

**Closed by cyberteenie** 2023-10-23 05:56 UTC
Labels: bug, sla, client-input-required
